; Beast 1.0 — CODE 2 disassembly (generated by tools/disasm.py)
; A5 world: above=224 below=1902

; ======================================================================
; CODE 2  (4226 bytes)
; ======================================================================

; ---------- ERROR ----------
ERROR:
  0000  4E56FEEE             link.w   a6, #-274
  0004  206E0008             movea.l  $8(a6), a0
  0008  43EEFEF0             lea.l    -$110(a6), a1
  000C  703F                 moveq    #$3F, d0
L000E:
  000E  22D8                 move.l   (a0)+, (a1)+
  0010  51C8FFFC             dbra     d0, L000E
  0014  486EFEF0             pea.l    -$110(a6)
  0018  487A002C             pea.l    $46(pc)   ; data @0046
  001C  487A0026             pea.l    $44(pc)   ; data @0044
  0020  487A0020             pea.l    $42(pc)   ; data @0042
  0024  A98B                 _ParamText
  0026  554F                 subq.w   #$2, a7
  0028  3F3C0081             move.w   #$81, -(a7)
  002C  42A7                 clr.l    -(a7)
  002E  A985                 _Alert
  0030  3D5FFEEE             move.w   (a7)+, -$112(a6)
  0034  4E5E                 unlk     a6
  0036  2E9F                 move.l   (a7)+, (a7)
  0038  4E75                 rts      
  003A  4552524F52202020     dc.b    'ERROR'   ; MacsBug name
  0042  dc.b  00 16 00 12 00 12                                ......

; ---------- RAND ----------
RAND:
  0048  4E560000             link.w   a6, #0
  004C  554F                 subq.w   #$2, a7
  004E  A861                 _Random
  0050  302E0008             move.w   $8(a6), d0
  0054  5240                 addq.w   #$1, d0
  0056  321F                 move.w   (a7)+, d1
  0058  48C1                 ext.l    d1
  005A  83C0                 divs.w   d0, d1
  005C  4841                 swap     d1
  005E  4A41                 tst.w    d1
  0060  6A02                 bpl.b    L0064
  0062  4441                 neg.w    d1
L0064:
  0064  3D41000A             move.w   d1, $a(a6)
  0068  4E5E                 unlk     a6
  006A  205F                 movea.l  (a7)+, a0
  006C  544F                 addq.w   #$2, a7
  006E  4ED0                 jmp      (a0)
  0070  52414E4420202020     dc.b    'RAND'   ; MacsBug name

; ---------- GETPICT ----------
GETPICT:
  0078  4E560000             link.w   a6, #0
  007C  2F0C                 move.l   a4, -(a7)
  007E  286E000E             movea.l  $e(a6), a4
  0082  594F                 subq.w   #$4, a7
  0084  2F3C50494354         move.l   #$50494354, -(a7)
  008A  3F2E000C             move.w   $c(a6), -(a7)
  008E  A9A0                 _GetResource
  0090  289F                 move.l   (a7)+, (a4)
  0092  4A94                 tst.l    (a4)
  0094  6608                 bne.b    L009E
  0096  487A001A             pea.l    $b2(pc)   ; "PICT is nil."
  009A  4EBAFF64             jsr      ERROR(pc)
L009E:
  009E  285F                 movea.l  (a7)+, a4
  00A0  4E5E                 unlk     a6
  00A2  205F                 movea.l  (a7)+, a0
  00A4  4FEF000A             lea.l    $a(a7), a7
  00A8  4ED0                 jmp      (a0)
  00AA  4745545049435420     dc.b    'GETPICT'   ; MacsBug name
  00B2  dc.b  0C 50 49 43 54 20 69 73 20 6E 69 6C 2E 16        .PICT is nil..

; ---------- GETPICTU ----------
GETPICTU:
  00C0  4E56FFE6             link.w   a6, #-26
  00C4  486DFBF8             pea.l    gPics[0](a5)
  00C8  3F3C00C8             move.w   #$C8, -(a7)
  00CC  2F0E                 move.l   a6, -(a7)
  00CE  4EBAFFA8             jsr      GETPICT(pc)
  00D2  486DFC00             pea.l    gPics[2](a5)
  00D6  3F3C00CA             move.w   #$CA, -(a7)
  00DA  2F0E                 move.l   a6, -(a7)
  00DC  4EBAFF9A             jsr      GETPICT(pc)
  00E0  486DFBFC             pea.l    gPics[1](a5)
  00E4  3F3C00C9             move.w   #$C9, -(a7)
  00E8  2F0E                 move.l   a6, -(a7)
  00EA  4EBAFF8C             jsr      GETPICT(pc)
  00EE  4E5E                 unlk     a6
  00F0  4E75                 rts      
  00F2  4745545049435455     dc.b    'GETPICTU'   ; MacsBug name

; ---------- INITMATR ----------
INITMATR:
  00FA  4E56FFEC             link.w   a6, #-20
  00FE  48E70300             movem.l  d6-d7, -(a7)
  0102  7C01                 moveq    #$1, d6
L0104:
  0104  7E01                 moveq    #$1, d7
L0106:
  0106  3006                 move.w   d6, d0
  0108  C1FC0012             muls.w   #$12, d0
  010C  D047                 add.w    d7, d0
    ; Board[x,y] at A5-$40B + x*18 + y   (Board: array[1..31,1..18] of 0..3)
  010E  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0112  1BBC00030000         move.b   #$3, (a5, d0.w)
  0118  5247                 addq.w   #$1, d7
  011A  0C470012             cmpi.w   #$12, d7
  011E  6FE6                 ble.b    L0106
  0120  5246                 addq.w   #$1, d6
  0122  0C46001F             cmpi.w   #$1F, d6
  0126  6FDC                 ble.b    L0104
  0128  7C01                 moveq    #$1, d6
L012A:
  012A  3006                 move.w   d6, d0
  012C  C1FC0012             muls.w   #$12, d0
  0130  0640FBF6             addi.w   #$FBF6, d0   ; A5 gBoard[x,1]  (x*18)
  0134  1BBC00010000         move.b   #$1, (a5, d0.w)
  013A  3006                 move.w   d6, d0
  013C  C1FC0012             muls.w   #$12, d0
  0140  0640FC07             addi.w   #$FC07, d0   ; A5 gBoard[x,18] (x*18) / gBoard[1,y]
  0144  1BBC00010000         move.b   #$1, (a5, d0.w)
  014A  5246                 addq.w   #$1, d6
  014C  0C46001F             cmpi.w   #$1F, d6
  0150  6FD8                 ble.b    L012A
  0152  7E01                 moveq    #$1, d7
L0154:
  0154  41EDFC07             lea.l    -$3f9(a5), a0   ; A5 gBoard[x,18] (x*18) / gBoard[1,y]
  0158  11BC00017000         move.b   #$1, (a0, d7.w)
  015E  41EDFE23             lea.l    -$1dd(a5), a0   ; A5 gBoard[31,y]
  0162  11BC00017000         move.b   #$1, (a0, d7.w)
  0168  5247                 addq.w   #$1, d7
  016A  0C470012             cmpi.w   #$12, d7
  016E  6FE4                 ble.b    L0154
  0170  4CDF00C0             movem.l  (a7)+, d6-d7
  0174  4E5E                 unlk     a6
  0176  4E75                 rts      
  0178  494E49544D415452     dc.b    'INITMATR'   ; MacsBug name

; ---------- RANDOMMA ----------
RANDOMMA:
  0180  4E56FFE6             link.w   a6, #-26
  0184  48E70F00             movem.l  d4-d7, -(a7)
  0188  594F                 subq.w   #$4, a7
  018A  A975                 _TickCount
  018C  2B5FFF4E             move.l   (a7)+, qd.randSeed(a5)
  0190  283C0000022E         move.l   #$22E, d4
  0196  89EE0008             divs.w   $8(a6), d4
  019A  3D44FFE6             move.w   d4, -$1a(a6)
  019E  7A01                 moveq    #$1, d5
  01A0  6046                 bra.b    L01E8
L01A2:
  01A2  554F                 subq.w   #$2, a7
  01A4  3F3C001C             move.w   #$1C, -(a7)
  01A8  4EBAFE9E             jsr      RAND(pc)
  01AC  3C1F                 move.w   (a7)+, d6
  01AE  5446                 addq.w   #$2, d6
  01B0  554F                 subq.w   #$2, a7
  01B2  3F3C000F             move.w   #$F, -(a7)
  01B6  4EBAFE90             jsr      RAND(pc)
  01BA  3E1F                 move.w   (a7)+, d7
  01BC  5447                 addq.w   #$2, d7
  01BE  3006                 move.w   d6, d0
  01C0  C1FC0012             muls.w   #$12, d0
  01C4  D047                 add.w    d7, d0
  01C6  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  01CA  0C3500030000         cmpi.b   #$3, (a5, d0.w)
  01D0  66D0                 bne.b    L01A2
  01D2  3006                 move.w   d6, d0
  01D4  C1FC0012             muls.w   #$12, d0
  01D8  D047                 add.w    d7, d0
  01DA  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  01DE  1BBC00010000         move.b   #$1, (a5, d0.w)
  01E4  5245                 addq.w   #$1, d5
  01E6  6906                 bvs.b    L01EE
L01E8:
  01E8  BA6EFFE6             cmp.w    -$1a(a6), d5
  01EC  6FB4                 ble.b    L01A2
L01EE:
  01EE  3D6DFBBCFFE6         move.w   gNumBeasts(a5), -$1a(a6)
  01F4  7A01                 moveq    #$1, d5
  01F6  6058                 bra.b    L0250
L01F8:
  01F8  554F                 subq.w   #$2, a7
  01FA  3F3C001C             move.w   #$1C, -(a7)
  01FE  4EBAFE48             jsr      RAND(pc)
  0202  3C1F                 move.w   (a7)+, d6
  0204  5446                 addq.w   #$2, d6
  0206  554F                 subq.w   #$2, a7
  0208  3F3C000F             move.w   #$F, -(a7)
  020C  4EBAFE3A             jsr      RAND(pc)
  0210  3E1F                 move.w   (a7)+, d7
  0212  5447                 addq.w   #$2, d7
  0214  3006                 move.w   d6, d0
  0216  C1FC0012             muls.w   #$12, d0
  021A  D047                 add.w    d7, d0
  021C  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0220  0C3500020000         cmpi.b   #$2, (a5, d0.w)
  0226  67D0                 beq.b    L01F8
  0228  3005                 move.w   d5, d0
  022A  E540                 asl.w    #$2, d0
  022C  0640FBC8             addi.w   #$FBC8, d0   ; A5 gBeasts[i].v (i*4)
  0230  48750000             pea.l    (a5, d0.w)
  0234  3F06                 move.w   d6, -(a7)
  0236  3F07                 move.w   d7, -(a7)
  0238  A880                 _SetPt
  023A  3006                 move.w   d6, d0
  023C  C1FC0012             muls.w   #$12, d0
  0240  D047                 add.w    d7, d0
  0242  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0246  1BBC00020000         move.b   #$2, (a5, d0.w)
  024C  5245                 addq.w   #$1, d5
  024E  6906                 bvs.b    L0256
L0250:
  0250  BA6EFFE6             cmp.w    -$1a(a6), d5
  0254  6FA2                 ble.b    L01F8
L0256:
  0256  554F                 subq.w   #$2, a7
  0258  3F3C001C             move.w   #$1C, -(a7)
  025C  4EBAFDEA             jsr      RAND(pc)
  0260  3C1F                 move.w   (a7)+, d6
  0262  5446                 addq.w   #$2, d6
  0264  554F                 subq.w   #$2, a7
  0266  3F3C000F             move.w   #$F, -(a7)
  026A  4EBAFDDC             jsr      RAND(pc)
  026E  3E1F                 move.w   (a7)+, d7
  0270  5447                 addq.w   #$2, d7
  0272  3006                 move.w   d6, d0
  0274  C1FC0012             muls.w   #$12, d0
  0278  D047                 add.w    d7, d0
  027A  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  027E  0C3500020000         cmpi.b   #$2, (a5, d0.w)
  0284  67D0                 beq.b    L0256
  0286  486DFBF4             pea.l    gMan.v(a5)
  028A  3F06                 move.w   d6, -(a7)
  028C  3F07                 move.w   d7, -(a7)
  028E  A880                 _SetPt
  0290  3006                 move.w   d6, d0
  0292  C1FC0012             muls.w   #$12, d0
  0296  D047                 add.w    d7, d0
  0298  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  029C  42350000             clr.b    (a5, d0.w)
  02A0  4CDF00F0             movem.l  (a7)+, d4-d7
  02A4  4E5E                 unlk     a6
  02A6  205F                 movea.l  (a7)+, a0
  02A8  544F                 addq.w   #$2, a7
  02AA  4ED0                 jmp      (a0)
  02AC  52414E444F4D4D41     dc.b    'RANDOMMA'   ; MacsBug name

; ---------- DRAWMATR ----------
DRAWMATR:
  02B4  4E56FFE4             link.w   a6, #-28
  02B8  48E70300             movem.l  d6-d7, -(a7)
  02BC  2F2DFEF2             move.l   gWindow(a5), -(a7)
  02C0  A873                 _SetPort
  02C2  7E01                 moveq    #$1, d7
L02C4:
  02C4  7C01                 moveq    #$1, d6
L02C6:
  02C6  3006                 move.w   d6, d0
  02C8  C1FC0012             muls.w   #$12, d0
  02CC  D047                 add.w    d7, d0
  02CE  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  02D2  0C3500030000         cmpi.b   #$3, (a5, d0.w)
  02D8  6744                 beq.b    L031E
  02DA  486EFFE4             pea.l    -$1c(a6)
  02DE  3006                 move.w   d6, d0
  02E0  5340                 subq.w   #$1, d0
  02E2  E940                 asl.w    #$4, d0
  02E4  3F00                 move.w   d0, -(a7)
  02E6  3007                 move.w   d7, d0
  02E8  5340                 subq.w   #$1, d0
  02EA  E940                 asl.w    #$4, d0
  02EC  3F00                 move.w   d0, -(a7)
  02EE  3006                 move.w   d6, d0
  02F0  E940                 asl.w    #$4, d0
  02F2  3F00                 move.w   d0, -(a7)
  02F4  3007                 move.w   d7, d0
  02F6  E940                 asl.w    #$4, d0
  02F8  3F00                 move.w   d0, -(a7)
  02FA  A8A7                 _SetRect
  02FC  3006                 move.w   d6, d0
  02FE  C1FC0012             muls.w   #$12, d0
  0302  D047                 add.w    d7, d0
  0304  7200                 moveq    #$0, d1
  0306  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  030A  12350000             move.b   (a5, d0.w), d1
  030E  E541                 asl.w    #$2, d1
  0310  0641FBF8             addi.w   #$FBF8, d1   ; A5 gPics[cell]  (cell*4)
  0314  2F351000             move.l   (a5, d1.w), -(a7)
  0318  486EFFE4             pea.l    -$1c(a6)
  031C  A8F6                 _DrawPicture
L031E:
  031E  5246                 addq.w   #$1, d6
  0320  0C46001F             cmpi.w   #$1F, d6
  0324  6FA0                 ble.b    L02C6
  0326  5247                 addq.w   #$1, d7
  0328  0C470012             cmpi.w   #$12, d7
  032C  6F96                 ble.b    L02C4
  032E  4CDF00C0             movem.l  (a7)+, d6-d7
  0332  4E5E                 unlk     a6
  0334  4E75                 rts      
  0336  445241574D415452     dc.b    'DRAWMATR'   ; MacsBug name

; ---------- DRAWCLOC ----------
DRAWCLOC:
  033E  4E56FDD8             link.w   a6, #-552
  0342  2F2DFEF2             move.l   gWindow(a5), -(a7)
  0346  A873                 _SetPort
  0348  486EFEE8             pea.l    -$118(a6)
  034C  3F3C01A4             move.w   #$1A4, -(a7)
  0350  3F3C011B             move.w   #$11B, -(a7)
  0354  3F3C01E5             move.w   #$1E5, -(a7)
  0358  3F3C0127             move.w   #$127, -(a7)
  035C  A8A7                 _SetRect
  035E  486EFEE8             pea.l    -$118(a6)
  0362  A8A3                 _EraseRect
  0364  302DFBC2             move.w   gClock(a5), d0
  0368  48C0                 ext.l    d0
  036A  2F00                 move.l   d0, -(a7)
  036C  486EFEF0             pea.l    -$110(a6)
  0370  4EAD00CA             jsr      RT_NumToString   ; JT → CODE 1+1686
  0374  3F3C01A6             move.w   #$1A6, -(a7)
  0378  3F3C0125             move.w   #$125, -(a7)
  037C  A893                 _MoveTo
  037E  486EFDD8             pea.l    -$228(a6)
  0382  487A0028             pea.l    $3ac(pc)   ; "Time: "
  0386  486EFEF0             pea.l    -$110(a6)
  038A  3F3C0002             move.w   #$2, -(a7)
  038E  4EAD0042             jsr      RT_Concat   ; JT → CODE 1+0000
  0392  584F                 addq.w   #$4, a7
  0394  486EFDD8             pea.l    -$228(a6)
  0398  A884                 _DrawString
  039A  486EFEE8             pea.l    -$118(a6)
  039E  A8A1                 _FrameRect
  03A0  4E5E                 unlk     a6
  03A2  4E75                 rts      
  03A4  44524157434C4F43     dc.b    'DRAWCLOC'   ; MacsBug name
  03AC  dc.b  06 54 69 6D 65 3A 20 12                          .Time: .

; ---------- DRAWCELL ----------
DRAWCELL:
  03B4  4E56FFE0             link.w   a6, #-32
  03B8  48E70300             movem.l  d6-d7, -(a7)
  03BC  3E2E0008             move.w   $8(a6), d7
  03C0  3C2E000A             move.w   $a(a6), d6
  03C4  486EFFE8             pea.l    -$18(a6)
  03C8  3006                 move.w   d6, d0
  03CA  5340                 subq.w   #$1, d0
  03CC  E940                 asl.w    #$4, d0
  03CE  3F00                 move.w   d0, -(a7)
  03D0  3007                 move.w   d7, d0
  03D2  5340                 subq.w   #$1, d0
  03D4  E940                 asl.w    #$4, d0
  03D6  3F00                 move.w   d0, -(a7)
  03D8  3006                 move.w   d6, d0
  03DA  E940                 asl.w    #$4, d0
  03DC  3F00                 move.w   d0, -(a7)
  03DE  3007                 move.w   d7, d0
  03E0  E940                 asl.w    #$4, d0
  03E2  3F00                 move.w   d0, -(a7)
  03E4  A8A7                 _SetRect
  03E6  3006                 move.w   d6, d0
  03E8  C1FC0012             muls.w   #$12, d0
  03EC  D047                 add.w    d7, d0
  03EE  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  03F2  0C3500030000         cmpi.b   #$3, (a5, d0.w)
  03F8  6608                 bne.b    L0402
  03FA  486EFFE8             pea.l    -$18(a6)
  03FE  A8A3                 _EraseRect
  0400  6022                 bra.b    L0424
L0402:
  0402  3006                 move.w   d6, d0
  0404  C1FC0012             muls.w   #$12, d0
  0408  D047                 add.w    d7, d0
  040A  7200                 moveq    #$0, d1
  040C  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0410  12350000             move.b   (a5, d0.w), d1
  0414  E541                 asl.w    #$2, d1
  0416  0641FBF8             addi.w   #$FBF8, d1   ; A5 gPics[cell]  (cell*4)
  041A  2F351000             move.l   (a5, d1.w), -(a7)
  041E  486EFFE8             pea.l    -$18(a6)
  0422  A8F6                 _DrawPicture
L0424:
  0424  4CDF00C0             movem.l  (a7)+, d6-d7
  0428  4E5E                 unlk     a6
  042A  2E9F                 move.l   (a7)+, (a7)
  042C  4E75                 rts      
  042E  4452415743454C4C     dc.b    'DRAWCELL'   ; MacsBug name

; ---------- MANMOVE ----------
MANMOVE:
  0436  4E560000             link.w   a6, #0
  043A  2F0C                 move.l   a4, -(a7)
  043C  286E0008             movea.l  $8(a6), a4
  0440  302DFBF6             move.w   gMan.h(a5), d0
  0444  C1FC0012             muls.w   #$12, d0
  0448  322DFBF4             move.w   gMan.v(a5), d1
  044C  D041                 add.w    d1, d0
  044E  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0452  1BBC00030000         move.b   #$3, (a5, d0.w)
  0458  302CFFEE             move.w   -$12(a4), d0
  045C  C1FC0012             muls.w   #$12, d0
  0460  322CFFEC             move.w   -$14(a4), d1
  0464  D041                 add.w    d1, d0
  0466  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  046A  42350000             clr.b    (a5, d0.w)
  046E  3F2DFBF6             move.w   gMan.h(a5), -(a7)
  0472  3F2DFBF4             move.w   gMan.v(a5), -(a7)
  0476  4EBAFF3C             jsr      DRAWCELL(pc)
  047A  3F2CFFEE             move.w   -$12(a4), -(a7)
  047E  3F2CFFEC             move.w   -$14(a4), -(a7)
  0482  4EBAFF30             jsr      DRAWCELL(pc)
  0486  486DFBF4             pea.l    gMan.v(a5)
  048A  3F2CFFEE             move.w   -$12(a4), -(a7)
  048E  3F2CFFEC             move.w   -$14(a4), -(a7)
  0492  A880                 _SetPt
  0494  285F                 movea.l  (a7)+, a4
  0496  4E5E                 unlk     a6
  0498  205F                 movea.l  (a7)+, a0
  049A  504F                 addq.w   #$8, a7
  049C  4ED0                 jmp      (a0)
  049E  4D414E4D4F564520     dc.b    'MANMOVE'   ; MacsBug name

; ---------- PUSHBLOC ----------
PUSHBLOC:
  04A6  4E56FFA6             link.w   a6, #-90
  04AA  48E71F08             movem.l  d3-d7/a4, -(a7)
  04AE  286E0008             movea.l  $8(a6), a4
  04B2  3C2DFBF6             move.w   gMan.h(a5), d6
  04B6  DC6E000E             add.w    $e(a6), d6
  04BA  3E2DFBF4             move.w   gMan.v(a5), d7
  04BE  DE6E000C             add.w    $c(a6), d7
  04C2  4A6E000E             tst.w    $e(a6)
  04C6  6704                 beq.b    L04CC
  04C8  7601                 moveq    #$1, d3
  04CA  6002                 bra.b    L04CE
L04CC:
  04CC  4203                 clr.b    d3
L04CE:
  04CE  4204                 clr.b    d4
  04D0  4205                 clr.b    d5
L04D2:
  04D2  3F06                 move.w   d6, -(a7)
    ; set constant [1..31]
  04D4  487A00BE             pea.l    $594(pc)   ; data @0594
  04D8  486EFFC6             pea.l    -$3a(a6)
  04DC  3F3C0004             move.w   #$4, -(a7)
  04E0  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  04E4  486EFFC6             pea.l    -$3a(a6)
  04E8  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  04EC  56C0                 sne.b    d0
  04EE  3F07                 move.w   d7, -(a7)
    ; set constant [1..18]
  04F0  487A009E             pea.l    $590(pc)   ; data @0590
  04F4  486EFFA6             pea.l    -$5a(a6)
  04F8  3F3C0004             move.w   #$4, -(a7)
  04FC  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  0500  486EFFA6             pea.l    -$5a(a6)
  0504  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  0508  56C1                 sne.b    d1
  050A  C001                 and.b    d1, d0
  050C  673A                 beq.b    L0548
  050E  3006                 move.w   d6, d0
  0510  C1FC0012             muls.w   #$12, d0
  0514  D047                 add.w    d7, d0
  0516  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  051A  0C3500010000         cmpi.b   #$1, (a5, d0.w)
  0520  671C                 beq.b    L053E
  0522  3006                 move.w   d6, d0
  0524  C1FC0012             muls.w   #$12, d0
  0528  D047                 add.w    d7, d0
  052A  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  052E  0C3500020000         cmpi.b   #$2, (a5, d0.w)
  0534  6604                 bne.b    L053A
  0536  7A01                 moveq    #$1, d5
  0538  6010                 bra.b    L054A
L053A:
  053A  7801                 moveq    #$1, d4
  053C  600C                 bra.b    L054A
L053E:
  053E  DC6E000E             add.w    $e(a6), d6
  0542  DE6E000C             add.w    $c(a6), d7
  0546  6002                 bra.b    L054A
L0548:
  0548  7A01                 moveq    #$1, d5
L054A:
  054A  1004                 move.b   d4, d0
  054C  8005                 or.b     d5, d0
  054E  6782                 beq.b    L04D2
  0550  4A04                 tst.b    d4
  0552  6728                 beq.b    L057C
  0554  3006                 move.w   d6, d0
  0556  C1FC0012             muls.w   #$12, d0
  055A  D047                 add.w    d7, d0
  055C  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0560  1BBC00010000         move.b   #$1, (a5, d0.w)
  0566  3F06                 move.w   d6, -(a7)
  0568  3F07                 move.w   d7, -(a7)
  056A  4EBAFE48             jsr      DRAWCELL(pc)
  056E  3F2CFFEE             move.w   -$12(a4), -(a7)
  0572  3F2CFFEC             move.w   -$14(a4), -(a7)
  0576  2F0C                 move.l   a4, -(a7)
  0578  4EBAFEBC             jsr      MANMOVE(pc)
L057C:
  057C  4CDF10F8             movem.l  (a7)+, d3-d7/a4
  0580  4E5E                 unlk     a6
  0582  205F                 movea.l  (a7)+, a0
  0584  504F                 addq.w   #$8, a7
  0586  4ED0                 jmp      (a0)
  0588  50555348424C4F43     dc.b    'PUSHBLOC'   ; MacsBug name
  0590  dc.b  00 07 FF FE FF FF FF FE                          ........

; ---------- MOVEMANT ----------
MOVEMANT:
  0598  4E56FFAC             link.w   a6, #-84
  059C  302DFBF6             move.w   gMan.h(a5), d0
  05A0  D06E000A             add.w    $a(a6), d0
  05A4  3D40FFEE             move.w   d0, -$12(a6)
  05A8  302DFBF4             move.w   gMan.v(a5), d0
  05AC  D06E0008             add.w    $8(a6), d0
  05B0  3D40FFEC             move.w   d0, -$14(a6)
  05B4  3F2EFFEE             move.w   -$12(a6), -(a7)
  05B8  487A00AC             pea.l    $666(pc)   ; data @0666
  05BC  486EFFCC             pea.l    -$34(a6)
  05C0  3F3C0004             move.w   #$4, -(a7)
  05C4  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  05C8  486EFFCC             pea.l    -$34(a6)
  05CC  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  05D0  56C0                 sne.b    d0
  05D2  3F2EFFEC             move.w   -$14(a6), -(a7)
  05D6  487A008A             pea.l    $662(pc)   ; data @0662
  05DA  486EFFAC             pea.l    -$54(a6)
  05DE  3F3C0004             move.w   #$4, -(a7)
  05E2  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  05E6  486EFFAC             pea.l    -$54(a6)
  05EA  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  05EE  56C1                 sne.b    d1
  05F0  C001                 and.b    d1, d0
  05F2  6752                 beq.b    L0646
  05F4  302EFFEE             move.w   -$12(a6), d0
  05F8  C1FC0012             muls.w   #$12, d0
  05FC  322EFFEC             move.w   -$14(a6), d1
  0600  D041                 add.w    d1, d0
  0602  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0606  10350000             move.b   (a5, d0.w), d0
  060A  602E                 bra.b    L063A
L060C:
  060C  3F2EFFEE             move.w   -$12(a6), -(a7)
  0610  3F2EFFEC             move.w   -$14(a6), -(a7)
  0614  2F0E                 move.l   a6, -(a7)
  0616  4EBAFE1E             jsr      MANMOVE(pc)
  061A  602A                 bra.b    L0646
L061C:
  061C  3F2E000A             move.w   $a(a6), -(a7)
  0620  3F2E0008             move.w   $8(a6), -(a7)
  0624  2F0E                 move.l   a6, -(a7)
  0626  4EBAFE7E             jsr      PUSHBLOC(pc)
  062A  601A                 bra.b    L0646
L062C:
  062C  487A0026             pea.l    $654(pc)   ; "Dead Meat !!!"
  0630  4EBAF9CE             jsr      ERROR(pc)
  0634  422DFBC1             clr.b    gPlaying(a5)
  0638  600C                 bra.b    L0646
L063A:
  063A  5300                 subq.b   #$1, d0
  063C  67DE                 beq.b    L061C
  063E  5300                 subq.b   #$1, d0
  0640  67EA                 beq.b    L062C
  0642  5300                 subq.b   #$1, d0
  0644  67C6                 beq.b    L060C
L0646:
  0646  4E5E                 unlk     a6
  0648  2E9F                 move.l   (a7)+, (a7)
  064A  4E75                 rts      
  064C  4D4F56454D414E54     dc.b    'MOVEMANT'   ; MacsBug name
  0654  dc.b  0D 44 65 61 64 20 4D 65 61 74 20 21 21 21 00 07  .Dead Meat !!!..
  0664  dc.b  FF FE FF FF FF FE                                ......

; ---------- DOMOVEMA ----------
DOMOVEMA:
  066A  4E56FFC6             link.w   a6, #-58
  066E  48E70700             movem.l  d5-d7, -(a7)
  0672  3F2E0008             move.w   $8(a6), -(a7)
    ; set constant ['I'..'L']
  0676  487A006E             pea.l    $6e6(pc)   ; data @06E6
  067A  486EFFC6             pea.l    -$3a(a6)
  067E  3F3C000A             move.w   #$A, -(a7)
  0682  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  0686  486EFFC6             pea.l    -$3a(a6)
  068A  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  068E  673C                 beq.b    L06CC
  0690  3A2E0008             move.w   $8(a6), d5
  0694  0645FFB7             addi.w   #$FFB7, d5
  0698  3005                 move.w   d5, d0
  069A  6018                 bra.b    L06B4
L069C:
  069C  4246                 clr.w    d6
  069E  7EFF                 moveq    #$FF, d7
  06A0  6020                 bra.b    L06C2
L06A2:
  06A2  7CFF                 moveq    #$FF, d6
  06A4  4247                 clr.w    d7
  06A6  601A                 bra.b    L06C2
L06A8:
  06A8  4246                 clr.w    d6
  06AA  7E01                 moveq    #$1, d7
  06AC  6014                 bra.b    L06C2
L06AE:
  06AE  7C01                 moveq    #$1, d6
  06B0  4247                 clr.w    d7
  06B2  600E                 bra.b    L06C2
L06B4:
  06B4  67E6                 beq.b    L069C
  06B6  5340                 subq.w   #$1, d0
  06B8  67E8                 beq.b    L06A2
  06BA  5340                 subq.w   #$1, d0
  06BC  67EA                 beq.b    L06A8
  06BE  5340                 subq.w   #$1, d0
  06C0  67EC                 beq.b    L06AE
L06C2:
  06C2  3F06                 move.w   d6, -(a7)
  06C4  3F07                 move.w   d7, -(a7)
  06C6  4EBAFED0             jsr      MOVEMANT(pc)
  06CA  6006                 bra.b    L06D2
L06CC:
  06CC  3F3C0002             move.w   #$2, -(a7)
  06D0  A9C8                 _SysBeep
L06D2:
  06D2  4CDF00E0             movem.l  (a7)+, d5-d7
  06D6  4E5E                 unlk     a6
  06D8  205F                 movea.l  (a7)+, a0
  06DA  544F                 addq.w   #$2, a7
  06DC  4ED0                 jmp      (a0)
  06DE  444F4D4F56454D41     dc.b    'DOMOVEMA'   ; MacsBug name
  06E6  dc.b  1E 00 00 00 00 00 00 00 00 00                    ..........

; ---------- BEASTMOV ----------
BEASTMOV:
  06F0  4E560000             link.w   a6, #0
  06F4  2F07                 move.l   d7, -(a7)
  06F6  3E2E0010             move.w   $10(a6), d7
  06FA  3007                 move.w   d7, d0
  06FC  E540                 asl.w    #$2, d0
  06FE  0640FBCA             addi.w   #$FBCA, d0   ; A5 gBeasts[i].h (i*4)
  0702  30350000             move.w   (a5, d0.w), d0
  0706  C1FC0012             muls.w   #$12, d0
  070A  3207                 move.w   d7, d1
  070C  E541                 asl.w    #$2, d1
  070E  0641FBC8             addi.w   #$FBC8, d1   ; A5 gBeasts[i].v (i*4)
  0712  32351000             move.w   (a5, d1.w), d1
  0716  D041                 add.w    d1, d0
  0718  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  071C  1BBC00030000         move.b   #$3, (a5, d0.w)
  0722  302E000E             move.w   $e(a6), d0
  0726  C1FC0012             muls.w   #$12, d0
  072A  322E000C             move.w   $c(a6), d1
  072E  D041                 add.w    d1, d0
  0730  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0734  1BBC00020000         move.b   #$2, (a5, d0.w)
  073A  3007                 move.w   d7, d0
  073C  E540                 asl.w    #$2, d0
  073E  0640FBCA             addi.w   #$FBCA, d0   ; A5 gBeasts[i].h (i*4)
  0742  3F350000             move.w   (a5, d0.w), -(a7)
  0746  3007                 move.w   d7, d0
  0748  E540                 asl.w    #$2, d0
  074A  0640FBC8             addi.w   #$FBC8, d0   ; A5 gBeasts[i].v (i*4)
  074E  3F350000             move.w   (a5, d0.w), -(a7)
  0752  4EBAFC60             jsr      DRAWCELL(pc)
  0756  3F2E000E             move.w   $e(a6), -(a7)
  075A  3F2E000C             move.w   $c(a6), -(a7)
  075E  4EBAFC54             jsr      DRAWCELL(pc)
  0762  3007                 move.w   d7, d0
  0764  E540                 asl.w    #$2, d0
  0766  0640FBC8             addi.w   #$FBC8, d0   ; A5 gBeasts[i].v (i*4)
  076A  48750000             pea.l    (a5, d0.w)
  076E  3F2E000E             move.w   $e(a6), -(a7)
  0772  3F2E000C             move.w   $c(a6), -(a7)
  0776  A880                 _SetPt
  0778  2E1F                 move.l   (a7)+, d7
  077A  4E5E                 unlk     a6
  077C  205F                 movea.l  (a7)+, a0
  077E  4FEF000A             lea.l    $a(a7), a7
  0782  4ED0                 jmp      (a0)
  0784  42454153544D4F56     dc.b    'BEASTMOV'   ; MacsBug name

; ---------- MOVEBEAS ----------
MOVEBEAS:
  078C  4E56FFAA             link.w   a6, #-86
  0790  48E70F00             movem.l  d4-d7, -(a7)
  0794  3A2E000C             move.w   $c(a6), d5
  0798  3C05                 move.w   d5, d6
  079A  E546                 asl.w    #$2, d6
  079C  41EDFBCA             lea.l    gBeasts[0].h(a5), a0   ; A5 gBeasts[i].h (i*4)
  07A0  30306000             move.w   (a0, d6.w), d0
  07A4  D06E000A             add.w    $a(a6), d0
  07A8  3C00                 move.w   d0, d6
  07AA  3E05                 move.w   d5, d7
  07AC  E547                 asl.w    #$2, d7
  07AE  41EDFBC8             lea.l    gTimers[1](a5), a0   ; A5 gBeasts[i].v (i*4)
  07B2  30307000             move.w   (a0, d7.w), d0
  07B6  D06E0008             add.w    $8(a6), d0
  07BA  3E00                 move.w   d0, d7
  07BC  3F06                 move.w   d6, -(a7)
  07BE  487A0126             pea.l    $8e6(pc)   ; data @08E6
  07C2  486EFFCA             pea.l    -$36(a6)
  07C6  3F3C0004             move.w   #$4, -(a7)
  07CA  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  07CE  486EFFCA             pea.l    -$36(a6)
  07D2  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  07D6  56C0                 sne.b    d0
  07D8  3F07                 move.w   d7, -(a7)
  07DA  487A0106             pea.l    $8e2(pc)   ; data @08E2
  07DE  486EFFAA             pea.l    -$56(a6)
  07E2  3F3C0004             move.w   #$4, -(a7)
  07E6  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  07EA  486EFFAA             pea.l    -$56(a6)
  07EE  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  07F2  56C1                 sne.b    d1
  07F4  C001                 and.b    d1, d0
  07F6  670000C8             beq.w    L08C0
  07FA  3006                 move.w   d6, d0
  07FC  C1FC0012             muls.w   #$12, d0
  0800  D047                 add.w    d7, d0
  0802  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  0806  10350000             move.b   (a5, d0.w), d0
  080A  600000A6             bra.w    L08B2
L080E:
  080E  3006                 move.w   d6, d0
  0810  C1FC0012             muls.w   #$12, d0
  0814  D047                 add.w    d7, d0
  0816  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  081A  4A350000             tst.b    (a5, d0.w)
  081E  6604                 bne.b    L0824
  0820  7801                 moveq    #$1, d4
  0822  6002                 bra.b    L0826
L0824:
  0824  4204                 clr.b    d4
L0826:
  0826  3F05                 move.w   d5, -(a7)
  0828  3F06                 move.w   d6, -(a7)
  082A  3F07                 move.w   d7, -(a7)
  082C  2F0E                 move.l   a6, -(a7)
  082E  4EBAFEC0             jsr      BEASTMOV(pc)
  0832  4A04                 tst.b    d4
  0834  6700008A             beq.w    L08C0
  0838  487A009A             pea.l    $8d4(pc)   ; "Dead Meat!!!"
  083C  4EBAF7C2             jsr      ERROR(pc)
  0840  422DFBC1             clr.b    gPlaying(a5)
  0844  6000007A             bra.w    L08C0
L0848:
  0848  554F                 subq.w   #$2, a7
  084A  3F3C0002             move.w   #$2, -(a7)
  084E  4EBAF7F8             jsr      RAND(pc)
  0852  301F                 move.w   (a7)+, d0
  0854  5340                 subq.w   #$1, d0
  0856  3D40000A             move.w   d0, $a(a6)
  085A  554F                 subq.w   #$2, a7
  085C  3F3C0002             move.w   #$2, -(a7)
  0860  4EBAF7E6             jsr      RAND(pc)
  0864  301F                 move.w   (a7)+, d0
  0866  5340                 subq.w   #$1, d0
  0868  3D400008             move.w   d0, $8(a6)
  086C  3C05                 move.w   d5, d6
  086E  E546                 asl.w    #$2, d6
  0870  41EDFBCA             lea.l    gBeasts[0].h(a5), a0   ; A5 gBeasts[i].h (i*4)
  0874  30306000             move.w   (a0, d6.w), d0
  0878  D06E000A             add.w    $a(a6), d0
  087C  3C00                 move.w   d0, d6
  087E  3E05                 move.w   d5, d7
  0880  E547                 asl.w    #$2, d7
  0882  41EDFBC8             lea.l    gTimers[1](a5), a0   ; A5 gBeasts[i].v (i*4)
  0886  30307000             move.w   (a0, d7.w), d0
  088A  D06E0008             add.w    $8(a6), d0
  088E  3E00                 move.w   d0, d7
  0890  3006                 move.w   d6, d0
  0892  C1FC0012             muls.w   #$12, d0
  0896  D047                 add.w    d7, d0
  0898  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  089C  0C3500030000         cmpi.b   #$3, (a5, d0.w)
  08A2  661C                 bne.b    L08C0
  08A4  3F05                 move.w   d5, -(a7)
  08A6  3F06                 move.w   d6, -(a7)
  08A8  3F07                 move.w   d7, -(a7)
  08AA  2F0E                 move.l   a6, -(a7)
  08AC  4EBAFE42             jsr      BEASTMOV(pc)
  08B0  600E                 bra.b    L08C0
L08B2:
  08B2  6700FF5A             beq.w    L080E
  08B6  5300                 subq.b   #$1, d0
  08B8  678E                 beq.b    L0848
  08BA  5500                 subq.b   #$2, d0
  08BC  6700FF50             beq.w    L080E
L08C0:
  08C0  4CDF00F0             movem.l  (a7)+, d4-d7
  08C4  4E5E                 unlk     a6
  08C6  205F                 movea.l  (a7)+, a0
  08C8  5C4F                 addq.w   #$6, a7
  08CA  4ED0                 jmp      (a0)
  08CC  4D4F564542454153     dc.b    'MOVEBEAS'   ; MacsBug name
  08D4  dc.b  0C 44 65 61 64 20 4D 65 61 74 21 21 21 16 00 07  .Dead Meat!!!...
  08E4  dc.b  FF FE FF FF FF FE                                ......

; ---------- OPENSPAC ----------
OPENSPAC:
  08EA  4E56FFC6             link.w   a6, #-58
  08EE  48E70700             movem.l  d5-d7, -(a7)
  08F2  4205                 clr.b    d5
  08F4  302E000E             move.w   $e(a6), d0
  08F8  5340                 subq.w   #$1, d0
  08FA  322E000E             move.w   $e(a6), d1
  08FE  5241                 addq.w   #$1, d1
  0900  3D41FFE8             move.w   d1, -$18(a6)
  0904  3C00                 move.w   d0, d6
  0906  6052                 bra.b    L095A
L0908:
  0908  302E000C             move.w   $c(a6), d0
  090C  5340                 subq.w   #$1, d0
  090E  322E000C             move.w   $c(a6), d1
  0912  5241                 addq.w   #$1, d1
  0914  3D41FFE6             move.w   d1, -$1a(a6)
  0918  3E00                 move.w   d0, d7
  091A  6034                 bra.b    L0950
L091C:
  091C  3006                 move.w   d6, d0
  091E  C1FC0012             muls.w   #$12, d0
  0922  D047                 add.w    d7, d0
  0924  7200                 moveq    #$0, d1
  0926  0640FBF5             addi.w   #$FBF5, d0   ; A5 gBoard[x,y]  (x*18 + y)
  092A  12350000             move.b   (a5, d0.w), d1
  092E  3F01                 move.w   d1, -(a7)
    ; set constant [0, 3]  (man or empty)
  0930  487A0046             pea.l    $978(pc)   ; data @0978
  0934  486EFFC6             pea.l    -$3a(a6)
  0938  3F3C0002             move.w   #$2, -(a7)
  093C  4EAD0072             jsr      RT_SetLoad   ; JT → CODE 1+0DCE
  0940  486EFFC6             pea.l    -$3a(a6)
  0944  4EAD007A             jsr      RT_SetIn   ; JT → CODE 1+0E1A
  0948  6702                 beq.b    L094C
  094A  7A01                 moveq    #$1, d5
L094C:
  094C  5247                 addq.w   #$1, d7
  094E  6906                 bvs.b    L0956
L0950:
  0950  BE6EFFE6             cmp.w    -$1a(a6), d7
  0954  6FC6                 ble.b    L091C
L0956:
  0956  5246                 addq.w   #$1, d6
  0958  6906                 bvs.b    L0960
L095A:
  095A  BC6EFFE8             cmp.w    -$18(a6), d6
  095E  6FA8                 ble.b    L0908
L0960:
  0960  1D450010             move.b   d5, $10(a6)
  0964  4CDF00E0             movem.l  (a7)+, d5-d7
  0968  4E5E                 unlk     a6
  096A  205F                 movea.l  (a7)+, a0
  096C  504F                 addq.w   #$8, a7
  096E  4ED0                 jmp      (a0)
  0970  4F50454E53504143     dc.b    'OPENSPAC'   ; MacsBug name
  0978  dc.b  00 09                                            ..

; ---------- DOMOVEBE ----------
DOMOVEBE:
  097A  4E56FFE6             link.w   a6, #-26
  097E  48E70F08             movem.l  d4-d7/a4, -(a7)
  0982  7801                 moveq    #$1, d4
  0984  3D6DFBBCFFE6         move.w   gNumBeasts(a5), -$1a(a6)
  098A  7E01                 moveq    #$1, d7
  098C  60000098             bra.w    L0A26
L0990:
  0990  554F                 subq.w   #$2, a7
  0992  3007                 move.w   d7, d0
  0994  E540                 asl.w    #$2, d0
  0996  0640FBCA             addi.w   #$FBCA, d0   ; A5 gBeasts[i].h (i*4)
  099A  3F350000             move.w   (a5, d0.w), -(a7)
  099E  3007                 move.w   d7, d0
  09A0  E540                 asl.w    #$2, d0
  09A2  0640FBC8             addi.w   #$FBC8, d0   ; A5 gBeasts[i].v (i*4)
  09A6  3F350000             move.w   (a5, d0.w), -(a7)
  09AA  2F0E                 move.l   a6, -(a7)
  09AC  4EBAFF3C             jsr      OPENSPAC(pc)
  09B0  4A1F                 tst.b    (a7)+
  09B2  6700006E             beq.w    L0A22
  09B6  4204                 clr.b    d4
  09B8  554F                 subq.w   #$2, a7
  09BA  3F3C0002             move.w   #$2, -(a7)
  09BE  4EBAF688             jsr      RAND(pc)
  09C2  3A1F                 move.w   (a7)+, d5
  09C4  5345                 subq.w   #$1, d5
  09C6  554F                 subq.w   #$2, a7
  09C8  3F3C0002             move.w   #$2, -(a7)
  09CC  4EBAF67A             jsr      RAND(pc)
  09D0  3C1F                 move.w   (a7)+, d6
  09D2  5346                 subq.w   #$1, d6
  09D4  3007                 move.w   d7, d0
  09D6  E540                 asl.w    #$2, d0
  09D8  0640FBC8             addi.w   #$FBC8, d0   ; A5 gBeasts[i].v (i*4)
  09DC  49F50000             lea.l    (a5, d0.w), a4
  09E0  3014                 move.w   (a4), d0
  09E2  B06DFBF4             cmp.w    gMan.v(a5), d0
  09E6  6F04                 ble.b    L09EC
  09E8  7CFF                 moveq    #$FF, d6
  09EA  600E                 bra.b    L09FA
L09EC:
  09EC  3014                 move.w   (a4), d0
  09EE  B06DFBF4             cmp.w    gMan.v(a5), d0
  09F2  6C04                 bge.b    L09F8
  09F4  7C01                 moveq    #$1, d6
  09F6  6002                 bra.b    L09FA
L09F8:
  09F8  4246                 clr.w    d6
L09FA:
  09FA  302C0002             move.w   $2(a4), d0
  09FE  B06DFBF6             cmp.w    gMan.h(a5), d0
  0A02  6F04                 ble.b    L0A08
  0A04  7AFF                 moveq    #$FF, d5
  0A06  6010                 bra.b    L0A18
L0A08:
  0A08  302C0002             move.w   $2(a4), d0
  0A0C  B06DFBF6             cmp.w    gMan.h(a5), d0
  0A10  6C04                 bge.b    L0A16
  0A12  7A01                 moveq    #$1, d5
  0A14  6002                 bra.b    L0A18
L0A16:
  0A16  4245                 clr.w    d5
L0A18:
  0A18  3F07                 move.w   d7, -(a7)
  0A1A  3F05                 move.w   d5, -(a7)
  0A1C  3F06                 move.w   d6, -(a7)
  0A1E  4EBAFD6C             jsr      MOVEBEAS(pc)
L0A22:
  0A22  5247                 addq.w   #$1, d7
  0A24  6908                 bvs.b    L0A2E
L0A26:
  0A26  BE6EFFE6             cmp.w    -$1a(a6), d7
  0A2A  6F00FF64             ble.w    L0990
L0A2E:
  0A2E  4A04                 tst.b    d4
  0A30  670C                 beq.b    L0A3E
  0A32  487A001A             pea.l    $a4e(pc)   ; "You Win!!!"
  0A36  4EBAF5C8             jsr      ERROR(pc)
  0A3A  422DFBC1             clr.b    gPlaying(a5)
L0A3E:
  0A3E  4CDF10F0             movem.l  (a7)+, d4-d7/a4
  0A42  4E5E                 unlk     a6
  0A44  4E75                 rts      
  0A46  444F4D4F56454245     dc.b    'DOMOVEBE'   ; MacsBug name
  0A4E  dc.b  0A 59 6F 75 20 57 69 6E 21 21 21 16              .You Win!!!.

; ---------- CHECKTIM ----------
CHECKTIM:
  0A5A  4E56FFEA             link.w   a6, #-22
  0A5E  48E70300             movem.l  d6-d7, -(a7)
  0A62  4207                 clr.b    d7
L0A64:
  0A64  7000                 moveq    #$0, d0
  0A66  1007                 move.b   d7, d0
  0A68  E540                 asl.w    #$2, d0
  0A6A  2F00                 move.l   d0, -(a7)
  0A6C  594F                 subq.w   #$4, a7
  0A6E  A975                 _TickCount
  0A70  221F                 move.l   (a7)+, d1
  0A72  201F                 move.l   (a7)+, d0
  0A74  0640FBC4             addi.w   #$FBC4, d0   ; A5 gTimers[t]   (t*4)
  0A78  B2B50000             cmp.l    (a5, d0.w), d1
  0A7C  6F3E                 ble.b    L0ABC
  0A7E  1007                 move.b   d7, d0
  0A80  601E                 bra.b    L0AA0
L0A82:
  0A82  4EBAFEF6             jsr      DOMOVEBE(pc)
  0A86  3C2DFBBE             move.w   gBeastDelay(a5), d6
  0A8A  48C6                 ext.l    d6
  0A8C  6018                 bra.b    L0AA6
L0A8E:
  0A8E  302DFBC2             move.w   gClock(a5), d0
  0A92  5240                 addq.w   #$1, d0
  0A94  3B40FBC2             move.w   d0, gClock(a5)
  0A98  4EBAF8A4             jsr      DRAWCLOC(pc)
  0A9C  7C3C                 moveq    #$3C, d6
  0A9E  6006                 bra.b    L0AA6
L0AA0:
  0AA0  67E0                 beq.b    L0A82
  0AA2  5300                 subq.b   #$1, d0
  0AA4  67E8                 beq.b    L0A8E
L0AA6:
  0AA6  594F                 subq.w   #$4, a7
  0AA8  A975                 _TickCount
  0AAA  201F                 move.l   (a7)+, d0
  0AAC  D086                 add.l    d6, d0
  0AAE  7200                 moveq    #$0, d1
  0AB0  1207                 move.b   d7, d1
  0AB2  E541                 asl.w    #$2, d1
  0AB4  0641FBC4             addi.w   #$FBC4, d1   ; A5 gTimers[t]   (t*4)
  0AB8  2B801000             move.l   d0, (a5, d1.w)
L0ABC:
  0ABC  5207                 addq.b   #$1, d7
  0ABE  0C070001             cmpi.b   #$1, d7
  0AC2  63A0                 bls.b    L0A64
  0AC4  4CDF00C0             movem.l  (a7)+, d6-d7
  0AC8  4E5E                 unlk     a6
  0ACA  4E75                 rts      
  0ACC  434845434B54494D     dc.b    'CHECKTIM'   ; MacsBug name

; ---------- CHECKMUL ----------
CHECKMUL:
  0AD4  4E560000             link.w   a6, #0
  0AD8  594F                 subq.w   #$4, a7
  0ADA  3F3C0060             move.w   #$60, -(a7)
  0ADE  1F3C0001             move.b   #$1, -(a7)
  0AE2  4EAD00C2             jsr      RT_NGetTrapAddress   ; JT → CODE 1+15CC
  0AE6  594F                 subq.w   #$4, a7
  0AE8  3F3C009F             move.w   #$9F, -(a7)
  0AEC  1F3C0001             move.b   #$1, -(a7)
  0AF0  4EAD00C2             jsr      RT_NGetTrapAddress   ; JT → CODE 1+15CC
  0AF4  201F                 move.l   (a7)+, d0
  0AF6  B09F                 cmp.l    (a7)+, d0
  0AF8  6606                 bne.b    L0B00
  0AFA  422DFE37             clr.b    gHasWNE(a5)
  0AFE  6006                 bra.b    L0B06
L0B00:
  0B00  1B7C0001FE37         move.b   #$1, gHasWNE(a5)
L0B06:
  0B06  1B7C0001FE36         move.b   #$1, gInForeground(a5)
  0B0C  4E5E                 unlk     a6
  0B0E  4E75                 rts      
  0B10  434845434B4D554C     dc.b    'CHECKMUL'   ; MacsBug name

; ---------- SETUPMEN ----------
SETUPMEN:
  0B18  4E56FFEE             link.w   a6, #-18
  0B1C  2F07                 move.l   d7, -(a7)
  0B1E  594F                 subq.w   #$4, a7
  0B20  3F3C0080             move.w   #$80, -(a7)
  0B24  A9BF                 _GetMenu
  0B26  2B5FFEF6             move.l   (a7)+, gMenus[1](a5)
  0B2A  2F2DFEF6             move.l   gMenus[1](a5), -(a7)
  0B2E  2F3C44525652         move.l   #$44525652, -(a7)
  0B34  A94D                 _AddResMenu
  0B36  594F                 subq.w   #$4, a7
  0B38  3F3C0081             move.w   #$81, -(a7)
  0B3C  A9BF                 _GetMenu
  0B3E  2B5FFEFA             move.l   (a7)+, gMenus[2](a5)
  0B42  594F                 subq.w   #$4, a7
  0B44  3F3C0082             move.w   #$82, -(a7)
  0B48  A9BF                 _GetMenu
  0B4A  2B5FFEFE             move.l   (a7)+, gMenus[3](a5)
  0B4E  7E01                 moveq    #$1, d7
L0B50:
  0B50  1007                 move.b   d7, d0
  0B52  4880                 ext.w    d0
  0B54  E540                 asl.w    #$2, d0
  0B56  0640FEF2             addi.w   #$FEF2, d0   ; A5 gMenus[i]    (i*4)
  0B5A  2F350000             move.l   (a5, d0.w), -(a7)
  0B5E  4267                 clr.w    -(a7)
  0B60  A935                 _InsertMenu
  0B62  5207                 addq.b   #$1, d7
  0B64  0C070003             cmpi.b   #$3, d7
  0B68  6FE6                 ble.b    L0B50
  0B6A  A937                 _DrawMenuBar
  0B6C  2E1F                 move.l   (a7)+, d7
  0B6E  4E5E                 unlk     a6
  0B70  4E75                 rts      
  0B72  53455455504D454E     dc.b    'SETUPMEN'   ; MacsBug name

; ---------- SETUPWIN ----------
SETUPWIN:
  0B7A  4E56FFFE             link.w   a6, #-2
  0B7E  594F                 subq.w   #$4, a7
  0B80  3F3C0080             move.w   #$80, -(a7)
  0B84  42A7                 clr.l    -(a7)
  0B86  70FF                 moveq    #$FF, d0
  0B88  2F00                 move.l   d0, -(a7)
  0B8A  A9BD                 _GetNewWindow
  0B8C  2B5FFEF2             move.l   (a7)+, gWindow(a5)
  0B90  2F2DFEF2             move.l   gWindow(a5), -(a7)
  0B94  A873                 _SetPort
  0B96  3F3C0009             move.w   #$9, -(a7)
  0B9A  A88A                 _TextSize
  0B9C  1D7C0001FFFE         move.b   #$1, -$2(a6)
  0BA2  7000                 moveq    #$0, d0
  0BA4  102EFFFE             move.b   -$2(a6), d0
  0BA8  3F00                 move.w   d0, -(a7)
  0BAA  A888                 _TextFace
  0BAC  4E5E                 unlk     a6
  0BAE  4E75                 rts      
  0BB0  534554555057494E     dc.b    'SETUPWIN'   ; MacsBug name

; ---------- REDRUM [JT 0xda] ----------
REDRUM:
  0BB8  4E560000             link.w   a6, #0
  0BBC  A9F4                 _ExitToShell
  0BBE  dc.b  4E 5E 4E 75 52 45 44 52 55 4D 20 20              N^NuREDRUM  

; ---------- INIT ----------
INIT:
  0BCA  4E560000             link.w   a6, #0
  0BCE  41EDFFCC             lea.l    qd.thePort(a5), a0
  0BD2  2F08                 move.l   a0, -(a7)
  0BD4  A86E                 _InitGraf
  0BD6  A912                 _InitWindows
  0BD8  A8FE                 _InitFonts
  0BDA  A930                 _InitMenus
  0BDC  A850                 _InitCursor
  0BDE  A9CC                 _TEInit
  0BE0  486D00DA             pea.l    REDRUM   ; JT → CODE 2+0BB8
  0BE4  A97B                 _InitDialogs
  0BE6  3F3CFFFF             move.w   #$FFFF, -(a7)
  0BEA  4267                 clr.w    -(a7)
  0BEC  201F                 move.l   (a7)+, d0
  0BEE  A032                 _FlushEvents
  0BF0  4EBAFEE2             jsr      CHECKMUL(pc)
  0BF4  4EBAFF22             jsr      SETUPMEN(pc)
  0BF8  4EBAFF80             jsr      SETUPWIN(pc)
  0BFC  422DFE41             clr.b    gDone(a5)
  0C00  4E5E                 unlk     a6
  0C02  4E75                 rts      
  0C04  494E495420202020     dc.b    'INIT'   ; MacsBug name

; ---------- MDESKABO ----------
MDESKABO:
  0C0C  4E56FFEE             link.w   a6, #-18
  0C10  2F07                 move.l   d7, -(a7)
  0C12  487A005E             pea.l    $c72(pc)   ; "1.0"
  0C16  487A0052             pea.l    $c6a(pc)   ; " 3/4/89"
  0C1A  487A004C             pea.l    $c68(pc)   ; data @0C68
  0C1E  487A0046             pea.l    $c66(pc)   ; data @0C66
  0C22  A98B                 _ParamText
  0C24  554F                 subq.w   #$2, a7
  0C26  3F3C0080             move.w   #$80, -(a7)
  0C2A  42A7                 clr.l    -(a7)
  0C2C  A985                 _Alert
  0C2E  3E1F                 move.w   (a7)+, d7
  0C30  0C470004             cmpi.w   #$4, d7
  0C34  660E                 bne.b    L0C44
  0C36  554F                 subq.w   #$2, a7
  0C38  3F3C0082             move.w   #$82, -(a7)
  0C3C  42A7                 clr.l    -(a7)
  0C3E  A985                 _Alert
  0C40  3E1F                 move.w   (a7)+, d7
  0C42  6012                 bra.b    L0C56
L0C44:
  0C44  0C470005             cmpi.w   #$5, d7
  0C48  660C                 bne.b    L0C56
  0C4A  554F                 subq.w   #$2, a7
  0C4C  3F3C0083             move.w   #$83, -(a7)
  0C50  42A7                 clr.l    -(a7)
  0C52  A985                 _Alert
  0C54  3E1F                 move.w   (a7)+, d7
L0C56:
  0C56  2E1F                 move.l   (a7)+, d7
  0C58  4E5E                 unlk     a6
  0C5A  2E9F                 move.l   (a7)+, (a7)
  0C5C  4E75                 rts      
  0C5E  4D4445534B41424F     dc.b    'MDESKABO'   ; MacsBug name
  0C66  dc.b  00 16 00 12 07 20 33 2F 34 2F 38 39 03 31 2E 30  ..... 3/4/89.1.0

; ---------- DOMENUBA ----------
DOMENUBA:
  0C76  4E56FEDC             link.w   a6, #-292
  0C7A  48E70300             movem.l  d6-d7, -(a7)
  0C7E  3C2E0008             move.w   $8(a6), d6
  0C82  3E2E000A             move.w   $a(a6), d7
  0C86  3006                 move.w   d6, d0
  0C88  600000D6             bra.w    L0D60
L0C8C:
  0C8C  0C470002             cmpi.w   #$2, d7
  0C90  6E0A                 bgt.b    L0C9C
  0C92  2F0E                 move.l   a6, -(a7)
  0C94  4EBAFF76             jsr      MDESKABO(pc)
  0C98  600000D6             bra.w    L0D70
L0C9C:
  0C9C  2F2DFEF6             move.l   gMenus[1](a5), -(a7)
  0CA0  3F07                 move.w   d7, -(a7)
  0CA2  486EFEEC             pea.l    -$114(a6)
  0CA6  A946                 _GetItem
  0CA8  486EFEE8             pea.l    -$118(a6)
  0CAC  A874                 _GetPort
  0CAE  554F                 subq.w   #$2, a7
  0CB0  486EFEEC             pea.l    -$114(a6)
  0CB4  A9B6                 _OpenDeskAcc
  0CB6  3D5FFEE6             move.w   (a7)+, -$11a(a6)
  0CBA  2F2EFEE8             move.l   -$118(a6), -(a7)
  0CBE  A873                 _SetPort
  0CC0  600000AE             bra.w    L0D70
L0CC4:
  0CC4  3007                 move.w   d7, d0
  0CC6  6060                 bra.b    L0D28
L0CC8:
  0CC8  4EBAF430             jsr      INITMATR(pc)
  0CCC  3F2DFBBA             move.w   gDensity(a5), -(a7)
  0CD0  4EBAF4AE             jsr      RANDOMMA(pc)
  0CD4  206DFEF2             movea.l  gWindow(a5), a0
  0CD8  48680010             pea.l    $10(a0)
  0CDC  A8A3                 _EraseRect
  0CDE  4EBAF5D4             jsr      DRAWMATR(pc)
  0CE2  426DFBC2             clr.w    gClock(a5)
  0CE6  42ADFBC4             clr.l    gTimers[0](a5)
  0CEA  42ADFBC8             clr.l    gTimers[1](a5)
  0CEE  1B7C0001FBC1         move.b   #$1, gPlaying(a5)
  0CF4  1B7C0001FBC0         move.b   #$1, gPaused(a5)
  0CFA  60000074             bra.w    L0D70
L0CFE:
  0CFE  4EAD003A             jsr      DOSETTIN   ; JT → CODE 1+1AE6
  0D02  3B6DFBB4FBBE         move.w   gSettings.delay+2(a5), gBeastDelay(a5)
  0D08  3B6DFBB0FBBC         move.w   gSettings.numBeasts+2(a5), gNumBeasts(a5)
  0D0E  3B6DFBB8FBBA         move.w   gSettings.density+2(a5), gDensity(a5)
  0D14  6000005A             bra.w    L0D70
L0D18:
  0D18  1B7C0001FBC0         move.b   #$1, gPaused(a5)
  0D1E  6050                 bra.b    L0D70
L0D20:
  0D20  1B7C0001FE41         move.b   #$1, gDone(a5)
  0D26  6048                 bra.b    L0D70
L0D28:
  0D28  5340                 subq.w   #$1, d0
  0D2A  679C                 beq.b    L0CC8
  0D2C  5340                 subq.w   #$1, d0
  0D2E  67CE                 beq.b    L0CFE
  0D30  5340                 subq.w   #$1, d0
  0D32  67E4                 beq.b    L0D18
  0D34  5340                 subq.w   #$1, d0
  0D36  67E8                 beq.b    L0D20
  0D38  6036                 bra.b    L0D70
L0D3A:
  0D3A  594F                 subq.w   #$4, a7
  0D3C  A924                 _FrontWindow
  0D3E  201F                 move.l   (a7)+, d0
  0D40  B0ADFEF2             cmp.l    gWindow(a5), d0
  0D44  660A                 bne.b    L0D50
  0D46  487A003E             pea.l    $d86(pc)   ; "Edit commands are currently for DAs only."
  0D4A  4EBAF2B4             jsr      ERROR(pc)
  0D4E  6020                 bra.b    L0D70
L0D50:
  0D50  554F                 subq.w   #$2, a7
  0D52  3007                 move.w   d7, d0
  0D54  5340                 subq.w   #$1, d0
  0D56  3F00                 move.w   d0, -(a7)
  0D58  A9C2                 _SysEdit
  0D5A  1D5FFEE5             move.b   (a7)+, -$11b(a6)
  0D5E  6010                 bra.b    L0D70
L0D60:
  0D60  5340                 subq.w   #$1, d0
  0D62  6700FF28             beq.w    L0C8C
  0D66  5340                 subq.w   #$1, d0
  0D68  6700FF5A             beq.w    L0CC4
  0D6C  5340                 subq.w   #$1, d0
  0D6E  67CA                 beq.b    L0D3A
L0D70:
  0D70  4267                 clr.w    -(a7)
  0D72  A938                 _HiliteMenu
  0D74  4CDF00C0             movem.l  (a7)+, d6-d7
  0D78  4E5E                 unlk     a6
  0D7A  2E9F                 move.l   (a7)+, (a7)
  0D7C  4E75                 rts      
  0D7E  444F4D454E554241     dc.b    'DOMENUBA'   ; MacsBug name
  0D86  dc.b  29 45 64 69 74 20 63 6F 6D 6D 61 6E 64 73 20 61  )Edit commands a
  0D96  dc.b  72 65 20 63 75 72 72 65 6E 74 6C 79 20 66 6F 72  re currently for
  0DA6  dc.b  20 44 41 73 20 6F 6E 6C 79 2E                     DAs only.

; ---------- DOMOUSED ----------
DOMOUSED:
  0DB0  4E56FFEE             link.w   a6, #-18
  0DB4  4A2DFBC0             tst.b    gPaused(a5)
  0DB8  6704                 beq.b    L0DBE
  0DBA  422DFBC0             clr.b    gPaused(a5)
L0DBE:
  0DBE  554F                 subq.w   #$2, a7
  0DC0  2F2DFE4C             move.l   gEvent.where(a5), -(a7)
  0DC4  486DFEEE             pea.l    gWhichWindow(a5)
  0DC8  A92C                 _FindWindow
  0DCA  301F                 move.w   (a7)+, d0
  0DCC  6056                 bra.b    L0E24
L0DCE:
  0DCE  486DFE42             pea.l    gEvent.what(a5)
  0DD2  2F2DFEEE             move.l   gWhichWindow(a5), -(a7)
  0DD6  A9B3                 _SystemClick
  0DD8  6000005E             bra.w    L0E38
L0DDC:
  0DDC  594F                 subq.w   #$4, a7
  0DDE  2F2DFE4C             move.l   gEvent.where(a5), -(a7)
  0DE2  A93D                 _MenuSelect
  0DE4  4EBAFE90             jsr      DOMENUBA(pc)
  0DE8  604E                 bra.b    L0E38
L0DEA:
  0DEA  3F3C0001             move.w   #$1, -(a7)
  0DEE  A9C8                 _SysBeep
  0DF0  6046                 bra.b    L0E38
L0DF2:
  0DF2  2F2DFEEE             move.l   gWhichWindow(a5), -(a7)
  0DF6  2F2DFE4C             move.l   gEvent.where(a5), -(a7)
  0DFA  486DFF58             pea.l    qd.screenBits.bounds(a5)
  0DFE  A925                 _DragWindow
  0E00  6036                 bra.b    L0E38
L0E02:
  0E02  202DFEEE             move.l   gWhichWindow(a5), d0
  0E06  B0ADFEF2             cmp.l    gWindow(a5), d0
  0E0A  662C                 bne.b    L0E38
  0E0C  554F                 subq.w   #$2, a7
  0E0E  2F2DFEEE             move.l   gWhichWindow(a5), -(a7)
  0E12  2F2DFE4C             move.l   gEvent.where(a5), -(a7)
  0E16  A91E                 _TrackGoAway
  0E18  4A1F                 tst.b    (a7)+
  0E1A  671C                 beq.b    L0E38
  0E1C  1B7C0001FE41         move.b   #$1, gDone(a5)
  0E22  6014                 bra.b    L0E38
L0E24:
  0E24  5340                 subq.w   #$1, d0
  0E26  67B4                 beq.b    L0DDC
  0E28  5340                 subq.w   #$1, d0
  0E2A  67A2                 beq.b    L0DCE
  0E2C  5340                 subq.w   #$1, d0
  0E2E  67BA                 beq.b    L0DEA
  0E30  5340                 subq.w   #$1, d0
  0E32  67BE                 beq.b    L0DF2
  0E34  5540                 subq.w   #$2, d0
  0E36  67CA                 beq.b    L0E02
L0E38:
  0E38  4E5E                 unlk     a6
  0E3A  4E75                 rts      
  0E3C  444F4D4F55534544     dc.b    'DOMOUSED'   ; MacsBug name

; ---------- DOKEYDOW ----------
DOKEYDOW:
  0E44  4E56FFEE             link.w   a6, #-18
  0E48  2F07                 move.l   d7, -(a7)
  0E4A  302DFE50             move.w   gEvent.modifiers(a5), d0
  0E4E  02400100             andi.w   #$100, d0
  0E52  4A40                 tst.w    d0
  0E54  671A                 beq.b    L0E70
  0E56  594F                 subq.w   #$4, a7
  0E58  202DFE44             move.l   gEvent.message(a5), d0
  0E5C  0280000000FF         andi.l   #$FF, d0
  0E62  3F00                 move.w   d0, -(a7)
  0E64  A93E                 _MenuKey
  0E66  4EBAFE0E             jsr      DOMENUBA(pc)
  0E6A  4267                 clr.w    -(a7)
  0E6C  A938                 _HiliteMenu
  0E6E  602E                 bra.b    L0E9E
L0E70:
  0E70  4A2DFBC1             tst.b    gPlaying(a5)
  0E74  6728                 beq.b    L0E9E
  0E76  2E2DFE44             move.l   gEvent.message(a5), d7
  0E7A  0287000000FF         andi.l   #$FF, d7
  0E80  0C47005A             cmpi.w   #$5A, d7
  0E84  6F08                 ble.b    L0E8E
  0E86  0647FF9F             addi.w   #$FF9F, d7
  0E8A  06470041             addi.w   #$41, d7
L0E8E:
  0E8E  3F07                 move.w   d7, -(a7)
  0E90  4EBAF7D8             jsr      DOMOVEMA(pc)
  0E94  4A2DFBC0             tst.b    gPaused(a5)
  0E98  6704                 beq.b    L0E9E
  0E9A  422DFBC0             clr.b    gPaused(a5)
L0E9E:
  0E9E  2E1F                 move.l   (a7)+, d7
  0EA0  4E5E                 unlk     a6
  0EA2  4E75                 rts      
  0EA4  444F4B4559444F57     dc.b    'DOKEYDOW'   ; MacsBug name

; ---------- DOUPDATE ----------
DOUPDATE:
  0EAC  4E56FFE8             link.w   a6, #-24
  0EB0  2F0C                 move.l   a4, -(a7)
  0EB2  286DFE44             movea.l  gEvent.message(a5), a4
  0EB6  486EFFEC             pea.l    -$14(a6)
  0EBA  A874                 _GetPort
  0EBC  2F0C                 move.l   a4, -(a7)
  0EBE  A873                 _SetPort
  0EC0  2F0C                 move.l   a4, -(a7)
  0EC2  A922                 _BeginUpdate
  0EC4  200C                 move.l   a4, d0
  0EC6  B0ADFEF2             cmp.l    gWindow(a5), d0
  0ECA  6608                 bne.b    L0ED4
  0ECC  4EBAF3E6             jsr      DRAWMATR(pc)
  0ED0  4EBAF46C             jsr      DRAWCLOC(pc)
L0ED4:
  0ED4  2F0C                 move.l   a4, -(a7)
  0ED6  A923                 _EndUpdate
  0ED8  2F2EFFEC             move.l   -$14(a6), -(a7)
  0EDC  A873                 _SetPort
  0EDE  285F                 movea.l  (a7)+, a4
  0EE0  4E5E                 unlk     a6
  0EE2  4E75                 rts      
  0EE4  444F555044415445     dc.b    'DOUPDATE'   ; MacsBug name

; ---------- DOMULTI ----------
DOMULTI:
  0EEC  4E56FFD4             link.w   a6, #-44
  0EF0  2F07                 move.l   d7, -(a7)
  0EF2  206E0008             movea.l  $8(a6), a0
  0EF6  43EEFFE0             lea.l    -$20(a6), a1
  0EFA  22D8                 move.l   (a0)+, (a1)+
  0EFC  22D8                 move.l   (a0)+, (a1)+
  0EFE  22D8                 move.l   (a0)+, (a1)+
  0F00  22D8                 move.l   (a0)+, (a1)+
  0F02  701F                 moveq    #$1F, d0
  0F04  2D40FFDA             move.l   d0, -$26(a6)
  0F08  2D6EFFE2FFD4         move.l   -$1e(a6), -$2c(a6)
  0F0E  7000                 moveq    #$0, d0
  0F10  102EFFD4             move.b   -$2c(a6), d0
  0F14  3E00                 move.w   d0, d7
  0F16  0C4700FA             cmpi.w   #$FA, d7
  0F1A  6606                 bne.b    L0F22
  0F1C  3F3C0001             move.w   #$1, -(a7)
  0F20  A9C8                 _SysBeep
L0F22:
  0F22  082E0000FFE5         btst.b   #$0, -$1b(a6)
  0F28  6708                 beq.b    L0F32
  0F2A  1B7C0001FE36         move.b   #$1, gInForeground(a5)
  0F30  6004                 bra.b    L0F36
L0F32:
  0F32  422DFE36             clr.b    gInForeground(a5)
L0F36:
  0F36  2E1F                 move.l   (a7)+, d7
  0F38  4E5E                 unlk     a6
  0F3A  2E9F                 move.l   (a7)+, (a7)
  0F3C  4E75                 rts      
  0F3E  444F4D554C544920     dc.b    'DOMULTI'   ; MacsBug name

; ---------- CHECKEVE ----------
CHECKEVE:
  0F46  4E56FFEA             link.w   a6, #-22
  0F4A  48E70300             movem.l  d6-d7, -(a7)
  0F4E  4A2DFE36             tst.b    gInForeground(a5)
  0F52  6704                 beq.b    L0F58
  0F54  4286                 clr.l    d6
  0F56  6002                 bra.b    L0F5A
L0F58:
  0F58  7C14                 moveq    #$14, d6
L0F5A:
  0F5A  4A2DFE37             tst.b    gHasWNE(a5)
  0F5E  6714                 beq.b    L0F74
  0F60  554F                 subq.w   #$2, a7
  0F62  3F3CFFFF             move.w   #$FFFF, -(a7)
  0F66  486DFE42             pea.l    gEvent.what(a5)
  0F6A  2F06                 move.l   d6, -(a7)
  0F6C  42A7                 clr.l    -(a7)
  0F6E  A860                 _WaitNextEvent
  0F70  1E1F                 move.b   (a7)+, d7
  0F72  6010                 bra.b    L0F84
L0F74:
  0F74  A9B4                 _SystemTask
  0F76  554F                 subq.w   #$2, a7
  0F78  3F3CFFFF             move.w   #$FFFF, -(a7)
  0F7C  486DFE42             pea.l    gEvent.what(a5)
  0F80  A970                 _GetNextEvent
  0F82  1E1F                 move.b   (a7)+, d7
L0F84:
  0F84  4A07                 tst.b    d7
  0F86  6748                 beq.b    L0FD0
  0F88  302DFE42             move.w   gEvent.what(a5), d0
  0F8C  602C                 bra.b    L0FBA
L0F8E:
  0F8E  102E0008             move.b   $8(a6), d0
  0F92  5300                 subq.b   #$1, d0
  0F94  673A                 beq.b    L0FD0
  0F96  4EBAFE18             jsr      DOMOUSED(pc)
  0F9A  6034                 bra.b    L0FD0
L0F9C:
  0F9C  102E0008             move.b   $8(a6), d0
  0FA0  5300                 subq.b   #$1, d0
  0FA2  672C                 beq.b    L0FD0
  0FA4  4EBAFE9E             jsr      DOKEYDOW(pc)
  0FA8  6026                 bra.b    L0FD0
L0FAA:
  0FAA  4EBAFF00             jsr      DOUPDATE(pc)
  0FAE  6020                 bra.b    L0FD0
L0FB0:
  0FB0  486DFE42             pea.l    gEvent.what(a5)
  0FB4  4EBAFF36             jsr      DOMULTI(pc)
  0FB8  6016                 bra.b    L0FD0
L0FBA:
  0FBA  5340                 subq.w   #$1, d0
  0FBC  67D0                 beq.b    L0F8E
  0FBE  5540                 subq.w   #$2, d0
  0FC0  67DA                 beq.b    L0F9C
  0FC2  5540                 subq.w   #$2, d0
  0FC4  67D6                 beq.b    L0F9C
  0FC6  5340                 subq.w   #$1, d0
  0FC8  67E0                 beq.b    L0FAA
  0FCA  0640FFF7             addi.w   #$FFF7, d0
  0FCE  67E0                 beq.b    L0FB0
L0FD0:
  0FD0  102DFBC0             move.b   gPaused(a5), d0
  0FD4  5300                 subq.b   #$1, d0
  0FD6  C02DFBC1             and.b    gPlaying(a5), d0
  0FDA  6704                 beq.b    L0FE0
  0FDC  4EBAFA7C             jsr      CHECKTIM(pc)
L0FE0:
  0FE0  4CDF00C0             movem.l  (a7)+, d6-d7
  0FE4  4E5E                 unlk     a6
  0FE6  205F                 movea.l  (a7)+, a0
  0FE8  544F                 addq.w   #$2, a7
  0FEA  4ED0                 jmp      (a0)
  0FEC  434845434B455645     dc.b    'CHECKEVE'   ; MacsBug name

; ---------- INITBEAS ----------
INITBEAS:
  0FF4  4E560000             link.w   a6, #0
  0FF8  4EAD002A             jsr      GETBEAST   ; JT → CODE 1+196A
  0FFC  3B6DFBB4FBBE         move.w   gSettings.delay+2(a5), gBeastDelay(a5)
  1002  3B6DFBB0FBBC         move.w   gSettings.numBeasts+2(a5), gNumBeasts(a5)
  1008  3B6DFBB8FBBA         move.w   gSettings.density+2(a5), gDensity(a5)
  100E  4EBAF0B0             jsr      GETPICTU(pc)
  1012  4EBAF0E6             jsr      INITMATR(pc)
  1016  422DFBC1             clr.b    gPlaying(a5)
  101A  422DFBC0             clr.b    gPaused(a5)
  101E  426DFBC2             clr.w    gClock(a5)
  1022  4E5E                 unlk     a6
  1024  4E75                 rts      
  1026  494E495442454153     dc.b    'INITBEAS'   ; MacsBug name

; ---------- SHUTDOWN ----------
SHUTDOWN:
  102E  4E560000             link.w   a6, #0
  1032  4EAD0032             jsr      SAVEBEAS   ; JT → CODE 1+1A62
  1036  2F2DFEF2             move.l   gWindow(a5), -(a7)
  103A  A914                 _DisposWindow
  103C  4E5E                 unlk     a6
  103E  4E75                 rts      
  1040  53485554444F574E     dc.b    'SHUTDOWN'   ; MacsBug name

; ---------- MAIN_ENTRY [JT 0xd2] ----------
MAIN_ENTRY:
  1048  4EAD0052             jsr      RT_InitGlobals   ; JT → CODE 1+0054
  104C  4EAD005A             jsr      RT_InitSANE   ; JT → CODE 1+009C
  1050  4EAD0062             jsr      RT_InitToolbox   ; JT → CODE 1+00B2

; ---------- BEASTIE ----------
BEASTIE:
  1054  4E560000             link.w   a6, #0
  1058  4EBAFB70             jsr      INIT(pc)
  105C  4EBAFF96             jsr      INITBEAS(pc)
L1060:
  1060  4227                 clr.b    -(a7)
  1062  4EBAFEE2             jsr      CHECKEVE(pc)
  1066  4A2DFE41             tst.b    gDone(a5)
  106A  67F4                 beq.b    L1060
  106C  4EBAFFC0             jsr      SHUTDOWN(pc)
  1070  4E5E                 unlk     a6
  1072  4EAD004A             jsr      RT_Halt   ; JT → CODE 1+0048
  1076  4E5E                 unlk     a6
  1078  4E75                 rts      
  107A  4245415354494520     dc.b    'BEASTIE'   ; MacsBug name
