"""Generate port artwork from the original resource fork.

  port/Sources/Beast/Artwork.swift   raw PICT bytes (rendered at runtime by PICT.swift)
  port/Resources/AppIcon.icns        app icon from ICN# 128 (32x32 1-bit + mask), scaled up

Usage: python3 tools/gen_artwork.py   (run from the repo root)
"""
import os, shutil, struct, subprocess, sys, tempfile, zlib
sys.path.insert(0, os.path.dirname(__file__))
import rsrc

ROOT = os.path.join(os.path.dirname(__file__), '..')
RES = rsrc.parse(open(os.path.join(ROOT, 'original', 'Beast 1.0.rsrc'), 'rb').read())

PICTS = [
    (200, 'man', 'cell 0 — the player'),
    (201, 'block', 'cell 1'),
    (202, 'beast', 'cell 2'),
    (128, 'aboutPicture', 'hand-drawn stick figure outside a house, in the About box (ALRT 128)'),
    (130, 'help', '"Help Playing Beast…" screen (ALRT 130)'),
    (131, 'info', '"Info On Beast, the Program" screen (ALRT 131)'),
]


def swift_artwork():
    out = ['// Generated by tools/gen_artwork.py from original/Beast 1.0.rsrc — do not edit.',
           '// Raw QuickDraw PICT (version 1) data, drawn by PICTImage.', '',
           'enum Artwork {']
    for rid, name, doc in PICTS:
        data = rsrc.get(RES, 'PICT', rid)
        out.append('    /// PICT %d: %s' % (rid, doc))
        out.append('    static let %s: [UInt8] = [' % name)
        for i in range(0, len(data), 16):
            out.append('        ' + ', '.join('0x%02X' % b for b in data[i:i + 16]) + ',')
        out.append('    ]')
    out.append('}')
    path = os.path.join(ROOT, 'port', 'Sources', 'Beast', 'Artwork.swift')
    open(path, 'w').write('\n'.join(out) + '\n')
    print('wrote', os.path.relpath(path, ROOT))


def png_rgba(path, size, pixels):
    raw = b''.join(b'\0' + bytes(c for px in row for c in px) for row in pixels)
    def chunk(t, b): return struct.pack('>I', len(b)) + t + b + struct.pack('>I', zlib.crc32(t + b))
    open(path, 'wb').write(b'\x89PNG\r\n\x1a\n'
                           + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0))
                           + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def icns():
    d = rsrc.get(RES, 'ICN#', 128)
    def bit(base, x, y): return d[base + y * 4 + x // 8] >> (7 - x % 8) & 1
    # Finder draws the mask white and the icon black on top.
    src = [[(0, 0, 0, 255) if bit(0, x, y) else (255, 255, 255, 255) if bit(128, x, y) else (0, 0, 0, 0)
            for x in range(32)] for y in range(32)]
    tmp = tempfile.mkdtemp()
    iconset = os.path.join(tmp, 'AppIcon.iconset')
    os.mkdir(iconset)
    # Nearest-neighbour scaling keeps the 1989 pixels crisp. The 32-pixel art is centred on a
    # 13/16 canvas so it sits inside the macOS icon grid instead of touching the edges.
    for pts in (16, 32, 128, 256, 512):
        for scale in (1, 2):
            n = pts * scale
            art = n * 13 // 16
            off = (n - art) // 2
            px = [[(0, 0, 0, 0)] * n for _ in range(n)]
            for y in range(art):
                for x in range(art):
                    px[off + y][off + x] = src[y * 32 // art][x * 32 // art]
            name = 'icon_%dx%d%s.png' % (pts, pts, '@2x' if scale == 2 else '')
            png_rgba(os.path.join(iconset, name), n, px)
    out = os.path.join(ROOT, 'port', 'Resources', 'AppIcon.icns')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    subprocess.check_call(['iconutil', '-c', 'icns', iconset, '-o', out])
    shutil.rmtree(tmp)
    print('wrote', os.path.relpath(out, ROOT))


if __name__ == '__main__':
    swift_artwork()
    icns()
